# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        poetry run pip install flake8 coveralls pytest-cov coverage[toml]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        poetry run pytest --cov=openbrokerapi
# FIXME THis fails due to missing toml support, somehow this should be posssible to preinstall like mentioned in the docs
#    - name: Coveralls
#      uses: AndreMiras/coveralls-python-action@develop
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        flag-name: run-${{ matrix.test_number }}
#        parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Coveralls Finished
#        uses: AndreMiras/coveralls-python-action@develop
#        with:
#          parallel-finished: true